"""Added __repr__ to Review model

Revision ID: 0826ab8327ad
Revises: 481752ed539b
Create Date: 2023-07-31 02:10:03.425454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0826ab8327ad'
down_revision = '481752ed539b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
